spring:
  application:
    name: resilient4j-boot3
server:
  port: 9898
resilience4j:
  circuitbreaker:
    instances:
      payService:
        registerHealthIndicator: true
        slidingWindowSize: 10              # Theo dõi 10 cuộc gọi gần nhất
        failureRateThreshold: 50           # Mở mạch nếu lỗi > 50%
        waitDurationInOpenState: 5s       # Chờ 15s trước khi thử lại (Half-Open)
  retry:
    instances:
      payService:
        maxAttempts: 3                     # Thử lại tối đa 3 lần
        waitDuration: 1s                   # Khoảng cách giữa các lần thử
  ratelimiter:
    instances:
      payService:
        limitForPeriod: 10                 # Tối đa 10 request
        limitRefreshPeriod: 1s             # Trong mỗi giây
        timeout-duration: 2s
  timelimiter:
    instances:
      payService:
        timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: '*'